Fixed problem with tuples in final_word_out and is_final.
There was a comma missing after self.label() in the ValueError raised by
final_word_out and is_final, causing a string formatting problem
("TypeError: not all arguments converted during string formatting") when
the label was a tuple.

EXAMPLE:
This was the behaviour previously to the commit:

    sage: A = Transducer(initial_states=[(0,0)])
    sage: A.state((0,0)).final_word_out = []
    Traceback (most recent call last):
    ...
    TypeError: not all arguments converted during string formatting

    sage: A = Transducer(final_states=[(0,0)])
    sage: A.state((0,0)).final_word_out = [1]
    sage: A.state((0,0)).is_final=False
    Traceback (most recent call last):
    ...
    TypeError: not all arguments converted during string formatting

This is the behaviour after the commit:

    sage: A = Transducer(initial_states=[(0,0)])
    sage: A.state((0,0)).final_word_out = []
    Traceback (most recent call last):
    ...
    ValueError: Only final states can have a final output word, but state (0, 0) is not final.

    sage: A = Transducer(final_states=[(0,0)])
    sage: A.state((0,0)).final_word_out = [1]
    sage: A.state((0,0)).is_final=False
    Traceback (most recent call last):
    ...
    ValueError: State (0, 0) cannot be non-final, because it has a final output word. Only final states can have a final output word.
    Traceback (most recent call last):