Asympt: fix compare_with_values() for interval coefficients
Previously:

sage: A.<n> = AsymptoticRing('n^ZZ', RBF)
sage: asy = (1 - 1/n + 1/n^2)/3 + O(1/n^3)
sage: asy.compare_with_values('n', lambda n: 1/(3+3/n), srange(5,10))
NotImplementedError: exactly one error term required