ginac: fix polynomial normalization for x^n if n is declared to be an integer
Previously we got for example:

sage: n = var('n'); assume(n,'integer'); assume(n>0); (e^(2*n)/(e^(2*n) - 1)).numerator()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-c745d1a68d96> in <module>
----> 1 n = var('n'); assume(n,'integer'); assume(n>Integer(0)); (e**(Integer(2)*n)/(e**(Integer(2)*n) - Integer(1))).numerator()

/usr/lib/python3.7/site-packages/sage/symbolic/expression.pyx in sage.symbolic.expression.Expression.numerator (build/cythonized/sage/symbolic/expression.cpp:51864)()
   9833             sig_on()
   9834             try:
-> 9835                 ex = self._gobj.numer()
   9836             finally:
   9837                 sig_off()

RuntimeError: power::degree(): undefined degree because of non-integer exponent